/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Home.Candidate;


import Entity.Worker;
import Model.UserDAO;
import Model.WorkerDAO;
import View.Login.LoginDetailFrame;
import java.awt.image.BufferedImage;
import java.io.IOException;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Asus
 */
public class DetailCandidate extends javax.swing.JPanel {

    /**
     * Creates new form Detail_Candidate
     */
    private DefaultListModel model;
    private int idUser;
    public DetailCandidate() {
        initComponents();
    }
    public DetailCandidate(int idUser) {
        initComponents();
        this.idUser = idUser;
        setImage();
        myInit();
    }
    
    private void setImage()
    {
        try 
        {
            BufferedImage imageMain;            
            imageMain = ImageIO.read(getClass().getResource("/icon/UV.png"));
            ImageIcon iconMain = new ImageIcon(imageMain.getScaledInstance(750 , 670, imageMain.SCALE_SMOOTH));
            DetailLabel.setIcon(iconMain);
        } catch (IOException ex) {
            Logger.getLogger(LoginDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void myInit()
    {
        UserDAO dao = new UserDAO();
        Vector<String> list = new Vector<>();
        try {
            list = dao.getJobData();
            ArrayList<Worker> workList = new ArrayList();
            workList = dao.getWorker(idUser);
            for (Worker worker : workList) 
            {
                String name = dao.getJobName(worker.getIdJob());
                cbxCandidateJob.addItem(name);
                jTextPane1.setText(worker.getDetail());
            }
        } catch(Exception e){
            e.printStackTrace();
        }
        listJob.setListData(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJob = new javax.swing.JList<>();
        cbxCandidateJob = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnDetailUpload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DetailLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel3.setPreferredSize(new java.awt.Dimension(1100, 825));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("Mô tả kỹ năng");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Công việc bạn có thể cung cấp:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        listJob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(listJob);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 350, 520));

        cbxCandidateJob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbxCandidateJob.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCandidateJobItemStateChanged(evt);
            }
        });
        jPanel3.add(cbxCandidateJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 328, 40));

        btnAdd.setBackground(new java.awt.Color(153, 153, 153));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdd.setText("Thêm vào danh sách của bạn");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 350, 70));

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemove.setText("Xóa");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 72, -1));

        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 407, 470, 270));

        btnDetailUpload.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDetailUpload.setText("Upload");
        btnDetailUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailUploadActionPerformed(evt);
            }
        });
        jPanel3.add(btnDetailUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 710, 201, 40));

        jLabel1.setBackground(new java.awt.Color(99, 136, 166));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ứng viên");
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 160));
        jPanel3.add(DetailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 750, 670));

        jLabel2.setBackground(new java.awt.Color(231, 245, 220));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Danh sách công việc");
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String value = "";
        value = listJob.getSelectedValue();
        boolean check = true;
        if(!value.equals(""))
        {
            int num = cbxCandidateJob.getItemCount();
            for(int i = 0; i < num; i ++)
            {
                if(cbxCandidateJob.getItemAt(i).equals(value))
                    check = false;
            }
            if(check == true)
                cbxCandidateJob.addItem(value);
        }
        else
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng để thêm vào danh sách tìm kiếm");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int index = cbxCandidateJob.getSelectedIndex();
        String value = cbxCandidateJob.getItemAt(index);
        UserDAO dao = new UserDAO();
        try {
            int idJob = dao.getIdOfJob(value);
            if(idJob >= 0)
            {
                boolean check = dao.checkExistWorker(idUser, idJob);
                if(check == true)
                    dao.removeWorker(idUser, idJob);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
        cbxCandidateJob.removeItemAt(index);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnDetailUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailUploadActionPerformed
        // TODO add your handling code here:
        String value = (String) cbxCandidateJob.getSelectedItem();
        UserDAO dao = new UserDAO();
        WorkerDAO workerDAO = new WorkerDAO();
        String detail = jTextPane1.getText();        
        try {
            int idJob = dao.getIdOfJob(value);
            boolean check = workerDAO.findWorker(idUser, idJob);
            if(check == false)
            {
                Worker worker = new Worker(idUser, idJob, detail);
                dao.addWorker(worker);
                JOptionPane.showMessageDialog(this, "Đăng tin thành công");
            }
            else
            {
                workerDAO.updateDetailWorker(idUser, idJob, detail);
                JOptionPane.showMessageDialog(this, "Sửa tin thahf công");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Thêm tin thất bại");
            Logger.getLogger(DetailCandidate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDetailUploadActionPerformed

    private void cbxCandidateJobItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCandidateJobItemStateChanged
        // TODO add your handling code here:
        String value = (String) cbxCandidateJob.getSelectedItem();
       UserDAO dao = new UserDAO();
        try {
            int idJob = dao.getIdOfJob(value);
            String content = dao.getContentOfWorker(idJob, idUser);
            jTextPane1.setText(content);
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbxCandidateJobItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DetailLabel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDetailUpload;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbxCandidateJob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JList<String> listJob;
    // End of variables declaration//GEN-END:variables
}
