/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Home.Candidate;

import View.Home.recruitment.*;
import View.Home.Candidate.*;
import Entity.Account;
import Entity.User;
import Model.UserDAO;
import View.Login.LoginDetailFrame;
import View.Login.RegisterFrame;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Asus
 */
public class Information extends javax.swing.JPanel {

    /**
     * Creates new form Information
     */
    private int idUser;
    public Information() {
        initComponents();
        boxChangePass.setSelected(false);
    }
    public Information(int idUser) 
    {
        initComponents();
        txtRegisPhone.setEditable(false);
        boxChangePass.setSelected(false);
        this.idUser = idUser;   
        setImage();
        myInit();
    }
    
    private void setImage()
    {
        try 
        {
            BufferedImage imageMain;            
            imageMain = ImageIO.read(getClass().getResource("/icon/UV.png"));
            ImageIcon iconMain = new ImageIcon(imageMain.getScaledInstance(1100 , 825, imageMain.SCALE_SMOOTH));
            ProfileLabel.setIcon(iconMain);
        } catch (IOException ex) {
            
        }
        
    }
    private void myInit()
    {
        try {
            UserDAO dao = new UserDAO();
            Account acc = dao.getAccOfUser(idUser);
            User can = dao.getInforOfUser(idUser);
            txtRegisPhone.setText(acc.getPhone());
            txtRegisName.setText(can.getName());
            String sex = can.getGender();
            if(sex.equals("1"))
                rdoSexMale.setSelected(true);
            else
                rdbSexFemale.setSelected(true);
            txtBirthDate.setText(can.getBirth());
            txtAddress.setText(can.getAddress());
            txtRegisEmail.setText(can.getEmail());
            jPasswordField1.setText(acc.getPassword());
            jPasswordField2.setText(acc.getPassword());
            txtRegisEmail.setText(can.getEmail());            
            cbxProvince.setSelectedItem(can.getProvince());
        } catch (SQLException ex) {
            Logger.getLogger(Information.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtRegisPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        boxChangePass = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRegisName = new javax.swing.JTextField();
        rdoSexMale = new javax.swing.JRadioButton();
        rdbSexFemale = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtBirthDate = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRegisEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbxProvince = new javax.swing.JComboBox<>();
        btnInforUpload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ProfileLabel = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setPreferredSize(new java.awt.Dimension(1100, 825));

        jPanel5.setPreferredSize(new java.awt.Dimension(1100, 825));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Số điện thoại");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Mật khẩu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Nhập lại mật khẩu");

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        boxChangePass.setText("Thay đổi mật khẩu");
        boxChangePass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                boxChangePassStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(boxChangePass, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegisPhone, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegisPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxChangePass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 620, 200));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Họ và tên");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Năm sinh");

        buttonGroup1.add(rdoSexMale);
        rdoSexMale.setText("Nam");

        buttonGroup1.add(rdbSexFemale);
        rdbSexFemale.setText("Nữ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Giới tính");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Địa chỉ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Tỉnh");

        txtRegisEmail.setText("ABC@.gmail.com");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Email");

        cbxProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Bà Rịa–Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu", "Bắc Nin", "Bến Tre", "Bình Ðịnh", "Bình Dương", "Bình Phướcc", "Bình Thuận", "Cà Mau", "Cần Thơ", "Cao Bằng", "Ðà Nẵng", "Ðắk Lắk", "Ðắk Nông", "Ðiện Biên", "Ðồng Nai", "Ðồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Duong", "Hải Phòng", "Hậu Giang", "TP.Hồ Chí Minh", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Ðồng", "Lạng Son", "Lào Cai", "Long An", "Nam Ðịnh", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên–Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vinh Long", "Vinh Phúc", "Yên Bái" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(rdoSexMale)
                                .addGap(47, 47, 47)
                                .addComponent(rdbSexFemale))
                            .addComponent(cbxProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress)
                            .addComponent(txtBirthDate)
                            .addComponent(txtRegisName)
                            .addComponent(txtRegisEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
                        .addGap(0, 58, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRegisName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSexMale)
                    .addComponent(rdbSexFemale)
                    .addComponent(jLabel11))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegisEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbxProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 620, 350));

        btnInforUpload.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInforUpload.setText("Upload");
        btnInforUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInforUploadActionPerformed(evt);
            }
        });
        jPanel5.add(btnInforUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 730, 280, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông tin tài khoản");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 100));
        jPanel5.add(ProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boxChangePassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_boxChangePassStateChanged
        // TODO add your handling code here:
        if(boxChangePass.isSelected())
        {
            jPasswordField1.setEnabled(true);
            jPasswordField2.setEnabled(true);
        }
        else
        {
            jPasswordField1.setEnabled(false);
            jPasswordField2.setEnabled(false);
        }
        
    }//GEN-LAST:event_boxChangePassStateChanged

    private void updateUser(User dto)
    {
       UserDAO dao = new UserDAO();
        try {
            dao.updateCadidate(dto);
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    private void updateAccount(String phone, String password, int idUser)
    {
        try {
            UserDAO dao = new UserDAO();
            if(boxChangePass.isSelected()){
                String hashed = BCrypt.hashpw(password, BCrypt.gensalt(12));
                dao.updateAccount(phone,hashed, idUser);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Thay đổi thất bại");            
            Logger.getLogger(Information.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Thay đổi thất bại");            
            Logger.getLogger(Information.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private String checkDateTime(String input)
    {
        String result = "";
            Calendar  calendar = Calendar.getInstance();
            
            try {
                if(!input.matches("[0-9]{1,2}/[0-9]{1,2}/[0-9]{1,4}")) throw new Exception("Wrong format (dd/MM/yyyy)");
                Scanner s = new Scanner(input);
                int year = 0;
                int month = 0;
                int day = 0;
                int i = 0;
                s.useDelimiter("/");
                while(s.hasNext())
                {
                    i++;
                    if(i == 1)
                        day = Integer.parseInt(s.next());
                    if(i == 2)
                        month = Integer.parseInt(s.next());
                    if(i == 3)
                        year = Integer.parseInt(s.next());
                }
                int currentyear = calendar.get(Calendar.YEAR);
                if( year == 0 || year > currentyear) throw new Exception("Year > 0 and <= "+currentyear);
                calendar.set(Calendar.YEAR, year);
                if(month == 0 || month > 12 ) throw new Exception("Month have to in ( 1-12 )");
                calendar.set(Calendar.MONTH, month-1);
                int maxday = calendar.getActualMaximum(Calendar.DAY_OF_MONTH);
                if(day == 0 || day > maxday) throw new Exception("Dday of month "+month+" <= "+maxday);
                calendar.set(Calendar.DAY_OF_MONTH, day);
                SimpleDateFormat format= new SimpleDateFormat("dd/MM/yyyy");
                Date date = calendar.getTime();
            } catch (Exception e) {
                result += e.getMessage();
            }
            return result;
    }
    private void btnInforUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInforUploadActionPerformed
        // TODO add your handling code here:
        String valid = "";
        String phone = txtRegisPhone.getText().trim();
//        boolean match = phone.matches("[0-9]{10}");
//        if(!match)
//            valid += "Số điện thoại không hợp lệ\n";
        String password = new String(jPasswordField1.getPassword());
        String password2 = new String(jPasswordField2.getPassword());
        if(password.equals("") || password2.equals("") || !password.equals(password2))
            valid += "Mật khẩu không được trống và phải trùng nhau\n";
        String name = txtRegisName.getText().trim();
        if(name.equals(""))
            valid += "Họ và tên không được trống\n";
        String sex;
        if(rdbSexFemale.isSelected())
            sex = "0";
        else
            sex = "1";
        String birth = txtBirthDate.getText();
        valid += checkDateTime(birth);
        int pos = cbxProvince.getSelectedIndex();
        String province = cbxProvince.getItemAt(pos).trim();
        String add = txtAddress.getText();
        if(add.equals(""))
            valid += "Địa chỉ không được trống";
        String email = txtRegisEmail.getText().trim();
        if(email.equals(""))
            valid += "Email không được trống";
        else
        {
            if (!email.matches("[^@]+@[^.@]+[.][^.@]+([.][^@.]+)?"))
                valid += "Email không hợp lệ";
        }
        if(!valid.equals(""))
            JOptionPane.showMessageDialog(this, valid);
        else
        {
            UserDAO dao = new UserDAO();
            User dto = new User(idUser,name, sex, birth, province, add, email);
            updateUser(dto);
            updateAccount(phone, password, idUser);                       
            JOptionPane.showMessageDialog(this, "Thay đổi thành công");            
        }
    }//GEN-LAST:event_btnInforUploadActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JCheckBox boxChangePass;
    private javax.swing.JButton btnInforUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxProvince;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton rdbSexFemale;
    private javax.swing.JRadioButton rdoSexMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtRegisEmail;
    private javax.swing.JTextField txtRegisName;
    private javax.swing.JTextField txtRegisPhone;
    // End of variables declaration//GEN-END:variables
}
