/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Login;

import DTO.Email;
import Model.EmailDAO;
import Model.UserDAO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author Asus
 */
public class PassForgetFrame extends javax.swing.JFrame {

    /**
     * Creates new form PassForgetFrame
     */
    EmailDAO emailDAO= new EmailDAO(new Email());
    int code=-1;
    UserDAO userDAO= new UserDAO();
    public PassForgetFrame() {
        initComponents();
        setVisibleCode(false);
        setVisiblePass(false);
        setImage();
        setLocationRelativeTo(null);
    }

    private void setImage()
    {
        try 
        {
            BufferedImage imageMain;            
            imageMain = ImageIO.read(getClass().getResource("/icon/Login.png"));
            ImageIcon iconMain = new ImageIcon(imageMain.getScaledInstance(710 , 860, imageMain.SCALE_SMOOTH));
            changePassLabel.setIcon(iconMain);
        } catch (IOException ex) {
            Logger.getLogger(LoginDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        btnGetCode = new javax.swing.JButton();
        jPanelCode = new javax.swing.JPanel();
        txtPass = new javax.swing.JPasswordField();
        btnChangePass = new javax.swing.JButton();
        txtPassCheck = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCheckCode = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        changePassLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 520));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 156, 319, 39));

        btnGetCode.setText("Get Code");
        btnGetCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCodeActionPerformed(evt);
            }
        });
        jPanel1.add(btnGetCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 99, 30));

        btnChangePass.setText("Set Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        jLabel1.setText("Password");

        jLabel2.setText("Password Check");

        javax.swing.GroupLayout jPanelCodeLayout = new javax.swing.GroupLayout(jPanelCode);
        jPanelCode.setLayout(jPanelCodeLayout);
        jPanelCodeLayout.setHorizontalGroup(
            jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass)
                    .addGroup(jPanelCodeLayout.createSequentialGroup()
                        .addComponent(btnChangePass)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addComponent(txtPassCheck))
                .addContainerGap())
        );
        jPanelCodeLayout.setVerticalGroup(
            jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCodeLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanelCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addComponent(btnChangePass)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        btnCheckCode.setText("Check Code");
        btnCheckCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckCodeActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, 39));

        txtEmail.setText("longpcse141128@fpt.edu.vn");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 96, 319, 30));

        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 97, -1, 37));

        lblCode.setText("Code");
        jPanel1.add(lblCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 167, 31, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Enter your email and Get code to check in your email !");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 25, 511, -1));

        changePassLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login.png"))); // NOI18N
        jPanel1.add(changePassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCodeActionPerformed
        if(!txtEmail.getText().matches("[0-9A-Z]{1,}@gmail.com")&&userDAO.checkEmail(txtEmail.getText())){
            JOptionPane.showMessageDialog(null,"Xin hãy chờ để nhận code xác nhận mail");
            code=emailDAO.EmailSend(txtEmail.getText());
            setVisibleCode(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"it not email");
        }
        
    }//GEN-LAST:event_btnGetCodeActionPerformed

    private void btnCheckCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckCodeActionPerformed
        // TODO add your handling code here:
        if(txtCode.getText().matches("[0-9]{1,}")){
           int codeCheck=Integer.parseInt(txtCode.getText());
           if(codeCheck==code){
                setVisiblePass(true);
           }
           else{
               JOptionPane.showMessageDialog(null,"wrong code");
           }
        }
        else{
            JOptionPane.showMessageDialog(null,"wrong format please enter Number");
        }
       
    }//GEN-LAST:event_btnCheckCodeActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        String password = new String(txtPass.getPassword());
        String repassword = new String(txtPassCheck.getPassword());
        if(!password.equals(repassword))
        {
            JOptionPane.showMessageDialog(this, "Both password not equals");
            return;
        }
        UserDAO dao = new UserDAO();
        try {
            String hashed = BCrypt.hashpw(password, BCrypt.gensalt(12));
            dao.changePassword(txtEmail.getText(), hashed);
            JOptionPane.showMessageDialog(this, "Success");
        } catch (Exception ex) {
            Logger.getLogger(PassForgetFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_btnChangePassActionPerformed
    private void setVisibleCode(boolean state){
        txtCode.setVisible(state);
        btnCheckCode.setVisible(state);
        lblCode.setVisible(state);
    }
    private void setVisiblePass(boolean state){
        jPanelCode.setVisible(state);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassForgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassForgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassForgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassForgetFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassForgetFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnCheckCode;
    private javax.swing.JButton btnGetCode;
    private javax.swing.JLabel changePassLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCode;
    private javax.swing.JLabel lblCode;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassCheck;
    // End of variables declaration//GEN-END:variables
}
