/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Home.recruitment;

import DTO.WorkerDTO;
import Entity.Job;
import Entity.User;
import Model.JobDAO;
import Model.WorkerDAO;
import View.Login.LoginDetailFrame;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class CandidateFind extends javax.swing.JPanel {

    /**
     * Creates new form CandidateFind
     */
    User user;
    WorkerDAO workerDAO= new WorkerDAO();
    JobDAO jobDAO= new JobDAO();
    Vector<Job> jobList= new Vector<>();
    Vector header= new Vector();
    public CandidateFind(User user) {
        initComponents();
        setImage();
        this.user=user;
        setJobList();
        header.add("Name Candidate");
        header.add("Detail");
        Vector<WorkerDTO> rows= new Vector<>();
        setTable(rows);
    }
    
    private void setImage()
    {
        try 
        {
            BufferedImage imageMain;            
            imageMain = ImageIO.read(getClass().getResource("/icon/UV.png"));
            ImageIcon iconMain = new ImageIcon(imageMain.getScaledInstance(1100 , 825, imageMain.SCALE_SMOOTH));
            findCanLabel.setIcon(iconMain);
        } catch (IOException ex) {
            Logger.getLogger(LoginDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void setJobList(){
        jobList = jobDAO.getAllJob();
        Vector<String> jobNames= new Vector<>();
        for(Job job:jobList){
            jobNames.add(job.getName());
        }
        DefaultComboBoxModel model= new DefaultComboBoxModel(jobNames);
        cbxCanJob.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCandidate = new javax.swing.JTable();
        btnFind = new javax.swing.JButton();
        cbxCanJob = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        findCanLabel = new javax.swing.JLabel();

        jPanel3.setPreferredSize(new java.awt.Dimension(1110, 825));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCandidate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCandidate);
        if (tblCandidate.getColumnModel().getColumnCount() > 0) {
            tblCandidate.getColumnModel().getColumn(0).setResizable(false);
            tblCandidate.getColumnModel().getColumn(1).setResizable(false);
            tblCandidate.getColumnModel().getColumn(2).setResizable(false);
            tblCandidate.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 237, 770, 530));

        btnFind.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel3.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 175, 150, -1));

        cbxCanJob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbxCanJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbxCanJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 129, 300, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tìm ứng viên");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 116));
        jPanel3.add(findCanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String name = (String) cbxCanJob.getSelectedItem();
        int id=getIDItem(name);
        if(id>=0){
            try {
               Vector<WorkerDTO> workerList= workerDAO.getAllWorkerByJobID(id);
               Vector data= new Vector();
               for(WorkerDTO worker:workerList){
                   Vector row= new Vector();
                   row.add(worker.getNameUser());
                   row.add(worker.getDetail());
                   data.add(row);
               }
                setTable(data);
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnFindActionPerformed
     
    private void setTable(Vector data){
          DefaultTableModel model= (DefaultTableModel) tblCandidate.getModel();
          model.setDataVector(data, header);
          
          tblCandidate.setModel(model);
    }
    private int getIDItem(String name){
        for(Job job:jobList){
            if(job.getName().equals(name)){
                return job.getId();
            }
        }
        return -1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JComboBox<String> cbxCanJob;
    private javax.swing.JLabel findCanLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCandidate;
    // End of variables declaration//GEN-END:variables
}
