/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Home.recruitment;

import Entity.RequirementJob;
import Entity.User;
import Model.JobDAO;
import Model.RatingDAO;
import Model.RequireJobDAO;
import View.Login.LoginDetailFrame;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class JobManagement extends javax.swing.JPanel {

    /**
     * Creates new form JobManagement
     */
    private User user;
    Vector header= new Vector();
    RequireJobDAO requireJobDAO= new RequireJobDAO();
    RatingDAO ratingDAO= new RatingDAO();
    Vector<RequirementJob> listRequirementJobs= new Vector<>();
    public JobManagement(User user) {
        initComponents();
        setImage();
        this.user=user;
        header.add("Job");
        header.add("Title");
        header.add("Status");
        header.add("Address");
        header.add("Rating");
        setTable(user);
    }
    
    private void setImage()
    {
        try 
        {
            BufferedImage imageMain;            
            imageMain = ImageIO.read(getClass().getResource("/icon/UV.png"));
            ImageIcon iconMain = new ImageIcon(imageMain.getScaledInstance(1100 , 825, imageMain.SCALE_SMOOTH));
            JobManaLabel.setIcon(iconMain);
        } catch (IOException ex) {
            Logger.getLogger(LoginDetailFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void setTable(User user){
       listRequirementJobs=requireJobDAO.findRequireJobByIdUser(user.getIdUser());
       JobDAO jobDAO= new JobDAO();
       
       DefaultTableModel defaultTableModel= (DefaultTableModel) tblJopManage.getModel();
       Vector data= new Vector();
        
       for(RequirementJob re:listRequirementJobs){
           System.out.println(re);
           Vector row= new Vector();
           row.add(jobDAO.getJobById(re.getIdJob()).getName());
           row.add(re.getTitle());
           if(re.getStatus()==1){
               row.add("Đang tìm kiếm");
           }
           else{
               row.add("Đã hủy");
           }
           row.add(re.getProvince());
           row.add(re.getRating());
           data.add(row);
       }
       
       defaultTableModel.setDataVector(data,header);
       tblJopManage.setModel(defaultTableModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJopManage = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        JobManaLabel = new javax.swing.JLabel();

        jPanel2.setPreferredSize(new java.awt.Dimension(1100, 825));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí công việc");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1100, 110));

        tblJopManage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJopManage);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 157, 1090, 516));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setText("Update");
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 691, 118, 39));

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 695, 106, -1));
        jPanel2.add(JobManaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        if(tblJopManage.getSelectedRowCount()==1&&!listRequirementJobs.isEmpty()){
            int i=tblJopManage.getSelectedRow();
          
            int idJob=listRequirementJobs.get(i).getIdJob();
            
            
            int check=requireJobDAO.deleteRequirementJobs(idJob);
            if(check>0){
                check=ratingDAO.deleteRating(idJob,user.getIdUser());
                if(check>0){
                    JOptionPane.showMessageDialog(null,"Remove Success ");
                    setTable(user);
            
                }
                else{
                    JOptionPane.showMessageDialog(null,"Remove Fail rating");
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Remove Fail job");
            }
        }
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JobManaLabel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJopManage;
    // End of variables declaration//GEN-END:variables
}
